aliases:
  - &restore-cache
    keys:
      - dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}-v1.0

  - &save-cache
    paths:
      - node_modules
    key: dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}-v1.0

version: 2
jobs:
  build:
    docker: 
      - image: node:10.5.0
    working_directory: ~/e-payments
    steps:
      - checkout
      - run: npm install firebase-tools
      - run: npm install
      - deploy:
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master