version: 2
jobs:
  build:
    docker: 
      - image: node:10.5.0
    working_directory: ~/e-payments
    steps:
      - run: apt-get update
      - run: apt-get install -y sudo
      - checkout
      - run: npm install firebase-tools
      - run: npm install
      - run: yarn build
      - deploy:
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master